# Generated by Django 5.1.15 on 2026-09-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=150)),
                ('company_name', models.CharField(default='NEXUS SOLUTIONS', max_length=100)),
                ('theme', models.CharField(default='midnight_gold', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Generated Card',
                'verbose_name_plural': 'Generated Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
