# Generated by Django 5.1.15 on 2026-09-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_conversational_card_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIKeyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField(help_text='AES-256 Fernet authenticated ciphertext')),
                ('key_hash', models.CharField(blank=True, help_text='SHA-256 hash fingerprint', max_length=64)),
                ('masked_key', models.CharField(blank=True, help_text='Safe masked preview e.g. sk-proj...1234', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenAI Key Configuration',
                'verbose_name_plural': 'OpenAI Key Configurations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='generatedcard',
                    name='theme',
                ),
                migrations.AddField(
                    model_name='generatedcard',
                    name='prompt',
                    field=models.TextField(default=''),
                ),
            ],
        ),
    ]
