# Generated by Django 5.1.15 on 2026-09-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_openaikeyconfig_remove_generatedcard_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmessage',
            name='image_base64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cardmessage',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
