# Generated by Django 5.2.17 on 2026-09-24 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Corporate Business Card', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('front_html', models.TextField(blank=True, default='')),
                ('back_html', models.TextField(blank=True, default='')),
                ('css', models.TextField(blank=True, default='')),
                ('card_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CardMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='reference_images/')),
                ('front_html', models.TextField(blank=True, default='')),
                ('back_html', models.TextField(blank=True, default='')),
                ('css', models.TextField(blank=True, default='')),
                ('card_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cards.cardsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
