# Generated by Django 5.2.17 on 2026-09-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmessage',
            name='image_base64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cardmessage',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cardmessage',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cardsession',
            name='image_base64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cardsession',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cardsession',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
